# set condition
on:
  push:
    branches: ["master"]

env:
  DOCKER_IMAGE_NAME: gitops
  HELM_REPO: chengdevith/reactjs-chart.git 
# build docker image and push it into docker hub
jobs:
  # ci
  ci-job:
    runs-on: ubuntu-latest
    environment: DOCKER_ENV
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Using commit SHA
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Show the SHA values
        run: |
          echo "TAG = ${{ env.TAG }}"
      - name: Docker login
        run: |
          echo "${{ secrets.TOKEN }}" | docker login -u ${{ secrets.USERNAME }} --password-stdin
      - name: Build & tag 
        run: |
          docker build -t ${{ secrets.USERNAME}}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }} .
      - name: Push to dockerhub
        run: |
          docker push ${{ secrets.USERNAME}}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }} 
      - name: Log from dockerhub
        if: always()
        run: | 
          docker logout
  # cd
  cd-job:
    needs: ci-job
    runs-on: ubuntu-latest
    environment: HEML_ENV
    steps:
      - name: Set commit SHA
        run: echo "TAG=${GITHUB_SHA::8}" >>$GITHUB_ENV

      - name: Checkout Helm repo
        uses: actions/checkout@v3
        with:
          repository: chengdevith/reactjs-chart
          path: helm_repo
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update Helm chart
        run: |
          cd helm_repo

          echo "Update repository username/image_name"
          yq -i ".image.repository=\"${{ secrets.USERNAME }}\"" values.yaml

          echo "Update image tag"
          yq -i ".image.tag=\"${{ env.TAG }}\"" values.yaml

          git config user.email "benz@gmail.com"
          git config user.name "benz"
          git add .
          git commit -m "update helm to use image ${{ env.TAG }}"

          # Simple push: token is already handled by checkout
          git push

      - name: Clean up
        run: rm -rf helm_repo